### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by yufengwhy** [yhs-968/pyGRU4REC#6]
```
mask = [] # indicator for the sessions to be terminated  
        finished = False          
        while not finished:  
            minlen = (end - start).min()
```

[Here](https://github.com/yufengwhy/pyGRU4REC/blob/master/modules/data.py#L115), `mask = [] ` should be within the while loop `while not finished:` ?

**Comment by yufengwhy** [comment]
```
        mask = [] # indicator for the sessions to be terminated
        finished = False        
        while not finished:
            minlen = (end - start).min()            
            for i in range(minlen - 1):
                # Build inputs & targets
                idx_input = df.item_idx.values[start]
                start += 1
                idx_target = df.item_idx.values[start]
                input = torch.LongTensor(idx_input)
                target = torch.LongTensor(idx_target)
                if i==1: mask = []
                yield input, target, mask, maskP          
            # see if how many sessions should terminate
            mask = np.arange(len(iters))[(end - start) == 1]
```
My trial for discussion, thanks a lot @yhs-968

**Comment by yufengwhy** [comment]
Q2: why `mask = np.arange(len(iters))[(end - start) <= 1]` is `<=` in  your code, `==` is enough ?

**Comment by yufengwhy** [comment]
Do you have time to check this issue? @yhs-968 Thanks a lot~

**Comment by yhs-968** [comment]
@yufengwhy Probably not until the next week.

**Comment by yhs-968** [comment]
What's the purpose of `if i==1: mask = []`? That line makes it impossible to deal with sessions with length > 2.

**Comment by yhs-968** [comment]
> @yufengwhy
> A1. No. If you do that, **all** sessions within session-parallel minibatches will be marked as terminated if any session terminates.
> A2. You're right. That part of the code comes from the original implementation by the authors of the GRU4REC paper. I didn't fix it because the code also works with `<=`.

By the way, I made a mistake in A1. Setting `mask=[]` is problematic since that line marks all sessions as **not** terminated. I've quickly skimmed over my code, but I'm not sure there's any critical error regarding the lines related to the `mask` variable.

However, it seems that you are using a new variable `maskP` for some purpose. If you've modified my original implementation, things might be different.

**Comment by yufengwhy** [comment]
for example, session s1 is with length 10000, other sessions are with length 5, `batchsize`==2, so `minlen` above always is 5: 
1. to the 1st `for loop`, i changes from 0 to 1,2,3,4, `mask `will be [0,1] after the loop; 
2. to the 2nd `for loop`,   `mask == [0,1]` only when` i==0`, then 

> reset (if i==1: mask = [])

to [] when `i==1,2,3,4`;
3. `mask `will be [0,1] after the 2nd `for loop`;
then the above 3 steps loop.

**Comment by yufengwhy** [comment]
But it's weird that the bug won't hurt any performance. thanks a lot for the `Instant Messaging` on github, lol ...

**Comment by yhs-968** [comment]
Agreed. It's a mystery...

**Comment by yhs-968** [comment]
bug fixed.
